source 'http://rubygems.org'

gem 'rails' , '2.3.5'
gem 'passenger', '4.0.53'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'json'
gem 'settingslogic'
gem 'rest-client'
gem 'composite_primary_keys'
gem 'mechanize', '1.0.0'
gem 'fastercsv'
gem 'rake', '0.9.2.2'
#gem 'rcov'
gem 'simplecov'
gem 'rdoc',  '3.8'
gem 'barby', '0.5.0'
gem 'rqrcode', '0.3.2'
gem 'rmagick'
gem 'mysql'
gem "iconv", "~> 1.0.3"
