--- 
cwd: /var/www/APPLICATIONS/mateme_v1/
log_file: /var/www/APPLICATIONS/mateme_v1/log/mongrel.log
port: 8000
environment: production
address: 0.0.0.0
pid_file:  /var/www/APPLICATIONS/mateme_v1/tmp/pids/mongrel.pid
servers: 3 
